apiVersion: v1
data:
  config.yaml: |
    branch-protection:
      orgs:
        hnaung:
          repos:
            https-github.com-hnaung-web-api-demo:
              required_status_checks:
                contexts:
                - pr-build
            jx-devsecops-demo:
              required_status_checks:
                contexts:
                - promotion-build
      protect-tested-repos: true
    github:
      LinkURL: null
    plank: {}
    pod_namespace: jx
    postsubmits:
      hnaung/https-github.com-hnaung-web-api-demo:
      - agent: tekton
        branches:
        - master
        name: release
        skip_report: true
      hnaung/jx-devsecops-demo:
      - agent: tekton
        branches:
        - master
        name: promotion
        skip_report: true
    presubmits:
      hnaung/https-github.com-hnaung-web-api-demo:
      - agent: tekton
        always_run: true
        context: pr-build
        name: pr-build
        rerun_command: /test this
        trigger: (?m)^/test( all| this),?(\s+|$)
      hnaung/jx-devsecops-demo:
      - agent: tekton
        always_run: true
        context: promotion-build
        name: promotion-build
        rerun_command: /test this
        trigger: (?m)^/test( all| this),?(\s+|$)
    prowjob_namespace: jx
    push_gateway:
      serve_metrics: false
    tide:
      context_options:
        from-branch-protection: true
        required-if-present-contexts: null
        skip-unknown-contexts: false
      merge_method:
        hnaung/https-github.com-hnaung-web-api-demo: merge
        hnaung/jx-devsecops-demo: merge
      queries:
      - labels:
        - approved
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - hnaung/jx-devsecops-demo
        - hnaung/https-github.com-hnaung-web-api-demo
      - labels:
        - updatebot
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - hnaung/jx-devsecops-demo
        - hnaung/https-github.com-hnaung-web-api-demo
      target_url: http://deck-jx.192.168.99.114.nip.io
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: config
  namespace: jx
